services:
  db:
    image: postgres:17.0
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRESS_USER=${DATABASE_USER}
      - POSTGRESS_DB=${DATABASE_NAME}
    volumes:
      - pgdata:\C:\Program Files\PostgreSQL\17\data
volumes:
  pgdata:
